### ISSUE TITLE
Article prompts need filtering for special characters that cannot be part of a valid file name

### ISSUE THREAD

**Issue by ciconsulting** [assafelovic/gpt-newspaper#7]
"FileNotFoundError: [Errno 2] No such file or directory: 'outputs/run_1706269702/The_US_GDP_Numbers,_opinion_of_Top_Fund_Managers_and/or_Bank_CEO.html'"

It looks like if the article prompt has characters that can't be part of a valid file name the program breaks before completing with an error message similar to the above.

**Comment by kushalshm1** [comment]
Can you tell me how to produce this error again?

**Comment by ciconsulting** [comment]
It looks to me like if you request an article that has a / in teh text. Like "Opinion of XYZ and/or ABC" it creates an invalid filename and the whole thing breaks. "/" needs to be either disallowed in the original request or better filtered out. There may be other special characters that cause the same or similar problem. I am pretty sure that in this case the problem is that "/" is not allowed as a file name.

**Comment by rotemweiss57** [comment]
@ciconsulting good catch, I will push a fix soon

**Comment by rotemweiss57** [comment]
thank you @sharma-aarushi!
